PA1: NUMERICAL PYTHON

1. NORMALIZATION PROBLEM

In [1]:
#Declaring nump as 'np'
import numpy as np

In [2]:
#Making a random 5x5 ndrray and storing it to variable X.
X = np.random.random((5,5))
X


array([[0.41132949, 0.07948157, 0.35154746, 0.7762611 , 0.69936359],
       [0.57979109, 0.59056226, 0.94132466, 0.81542448, 0.33626082],
       [0.9730527 , 0.55406788, 0.57401008, 0.42991721, 0.5717707 ],
       [0.58972784, 0.95353967, 0.89415591, 0.16898135, 0.99141859],
       [0.92639877, 0.66943433, 0.55830726, 0.793771  , 0.91762313]])

In [3]:
#To get the mean
m = X.mean()
m

0.64590091811302

In [5]:
#To get the sd
sd = X.std()
sd

0.25006514379801653

In [9]:
#Normalization
z = X-m//sd
z

np.save('X_normalized.npy', z)

2. DIVISIBLE BY 3 PROBLEM

In [8]:
#Declaring nump as 'np'
import numpy as np

#Creating an array of the first 100 positive integers
numbers = np.arange(1, 101)

#Square the numbers
squares = numbers ** 2

#Reshape into a 10 x 10 ndarray
A = squares.reshape(10, 10)

#Select all elements that are divisible by 3
div_by_3 = A[A % 3 == 0]

#Save the result into a .npy file
np.save("div_by_3.npy", div_by_3)

#Print
print("Matrix A (10x10 of squares):\n", A)
print("\nElements divisible by 3:\n", div_by_3)


Matrix A (10x10 of squares):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
